package org.example.clubmanager.service;

import com.lowagie.text.*;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import org.example.clubmanager.model.Club;
import org.springframework.stereotype.Service;

import java.awt.Color;
import java.io.IOException;
import java.io.OutputStream;
import java.util.List;

@Service
public class PdfService {

    public void generateClubsPdf(List<Club> clubs, OutputStream outputStream) throws IOException {
        Document document = new Document(PageSize.A4);
        PdfWriter.getInstance(document, outputStream);

        document.open();

        // Title
        Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 24, Color.BLUE);
        Paragraph title = new Paragraph("Champlain College Clubs", titleFont);
        title.setAlignment(Paragraph.ALIGN_CENTER);
        document.add(title);
        document.add(new Paragraph(" ")); // Spacer

        // Table
        PdfPTable table = new PdfPTable(2); // 2 columns: Name, Description
        table.setWidthPercentage(100);
        table.setSpacingBefore(10f);
        table.setSpacingAfter(10f);
        table.setWidths(new float[]{1f, 3f}); // Name column is narrower than Description

        // Header
        PdfPCell cell = new PdfPCell();
        cell.setBackgroundColor(Color.LIGHT_GRAY);
        cell.setPadding(5);
        
        Font headerFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD);

        cell.setPhrase(new Phrase("Club Name", headerFont));
        table.addCell(cell);

        cell.setPhrase(new Phrase("Description", headerFont));
        table.addCell(cell);

        // Data
        Font contentFont = FontFactory.getFont(FontFactory.HELVETICA);
        
        for (Club club : clubs) {
            table.addCell(new Phrase(club.getName(), contentFont));
            table.addCell(new Phrase(club.getDescription(), contentFont));
        }

        document.add(table);
        
        // Footer
        Paragraph footer = new Paragraph("Generated by Club Manager", FontFactory.getFont(FontFactory.HELVETICA_OBLIQUE, 10));
        footer.setAlignment(Paragraph.ALIGN_RIGHT);
        document.add(footer);

        document.close();
    }
}
